# Generated by Django 5.2.7 on 2025-10-18 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('anio', models.PositiveIntegerField(default=1)),
                ('cuatrimestre', models.PositiveIntegerField(default=1)),
                ('tipo_asignatura', models.CharField(choices=[('OBLIGATORIA', 'Obligatoria'), ('OPTATIVA', 'Optativa')], max_length=20)),
                ('tipo_duracion', models.CharField(choices=[('ANUAL', 'Anual'), ('CUATRIMESTRAL', 'Cuatrimestral')], max_length=20)),
                ('horas_teoria', models.PositiveIntegerField(default=0)),
                ('horas_practica', models.PositiveIntegerField(default=0)),
                ('horas_semanales', models.PositiveIntegerField(default=0)),
                ('horas_totales', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caracter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('TECNICATURA', 'Tecnicatura'), ('DIPLOMATURA', 'Diplomatura'), ('PREGRADO', 'Pregrado'), ('GRADO', 'Grado'), ('POSGRADO', 'Posgrado'), ('MAESTRIA', 'Maestria')], max_length=20)),
                ('esta_vigente', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dedicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarreraCoordinacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.carrera')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino')], db_index=True, max_length=20)),
                ('promocionable', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='gestion_academica.asignatura')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='instituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='gestion_academica.instituto'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(blank=True, choices=[('INFO', 'Info'), ('ALERTA', 'Alerta'), ('ADVERTENCIA', 'Advertencia'), ('SISTEMA', 'Sistema')], max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosRegimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_max_frente_alumnos', models.PositiveIntegerField()),
                ('horas_min_frente_alumnos', models.PositiveIntegerField()),
                ('horas_max_actual', models.PositiveIntegerField()),
                ('horas_min_actual', models.PositiveIntegerField()),
                ('max_asignaturas', models.PositiveIntegerField()),
                ('dedicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_regimen', to='gestion_academica.dedicacion')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_regimen', to='gestion_academica.modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Correlativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativa_requerida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_requisito_para', to='gestion_academica.planasignatura')),
                ('plan_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlativas_requeridas', to='gestion_academica.planasignatura')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDeEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('esta_vigente', models.BooleanField(default=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='planes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignaturas', models.ManyToManyField(related_name='planes_de_estudio', through='gestion_academica.PlanAsignatura', to='gestion_academica.asignatura')),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='gestion_academica.carrera')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='planasignatura',
            name='plan_de_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.plandeestudio'),
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('emisor', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tipo', 'emisor', 'numero', 'anio'), name='uq_resolucion')],
            },
        ),
        migrations.AddField(
            model_name='plandeestudio',
            name='resolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan', to='gestion_academica.resolucion'),
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_usuario', to='gestion_academica.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(related_name='usuarios', through='gestion_academica.RolUsuario', to='gestion_academica.rol'),
        ),
        migrations.CreateModel(
            name='UsuarioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='gestion_academica.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('carreras_coordinadas', models.ManyToManyField(related_name='coordinadores', through='gestion_academica.CarreraCoordinacion', to='gestion_academica.carrera')),
            ],
            options={
                'abstract': False,
            },
            bases=('gestion_academica.usuario',),
        ),
        migrations.AddField(
            model_name='carreracoordinacion',
            name='coordinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.coordinador'),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cantidad_materias', models.PositiveIntegerField(default=0)),
                ('caracter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='gestion_academica.caracter')),
                ('dedicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='gestion_academica.dedicacion')),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='gestion_academica.modalidad')),
            ],
            options={
                'abstract': False,
            },
            bases=('gestion_academica.usuario',),
        ),
        migrations.CreateModel(
            name='Designacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(blank=True, db_index=True, null=True)),
                ('tipo_designacion', models.CharField(choices=[('TEORICO', 'Teorico'), ('PRACTICO', 'Practico'), ('TEORICO + PRACTICO', 'Teorico + Practico')], max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='designaciones/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designaciones', to='gestion_academica.cargo')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designaciones', to='gestion_academica.comision')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designaciones', to='gestion_academica.parametrosregimen')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designaciones', to='gestion_academica.docente')),
            ],
        ),
        migrations.AddConstraint(
            model_name='comision',
            constraint=models.UniqueConstraint(fields=('asignatura', 'nombre'), name='uq_comision_asignatura_nombre'),
        ),
        migrations.AddConstraint(
            model_name='parametrosregimen',
            constraint=models.UniqueConstraint(fields=('modalidad', 'dedicacion'), name='uq_parametros_regimen'),
        ),
        migrations.AddConstraint(
            model_name='correlativa',
            constraint=models.UniqueConstraint(fields=('plan_asignatura', 'correlativa_requerida'), name='uq_correlativa'),
        ),
        migrations.AddIndex(
            model_name='planasignatura',
            index=models.Index(fields=['plan_de_estudio', 'asignatura'], name='gestion_aca_plan_de_c1ec6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='planasignatura',
            constraint=models.UniqueConstraint(fields=('plan_de_estudio', 'asignatura'), name='uq_plan_asignatura'),
        ),
        migrations.AddConstraint(
            model_name='rolusuario',
            constraint=models.UniqueConstraint(fields=('usuario', 'rol'), name='uq_usuario_rol'),
        ),
        migrations.AddConstraint(
            model_name='usuarionotificacion',
            constraint=models.UniqueConstraint(fields=('usuario', 'notificacion'), name='uq_usuario_notificacion'),
        ),
        migrations.AddConstraint(
            model_name='carreracoordinacion',
            constraint=models.UniqueConstraint(fields=('carrera', 'coordinador', 'fecha_inicio'), name='uq_carrera_coordinador_periodo'),
        ),
        migrations.AddConstraint(
            model_name='designacion',
            constraint=models.UniqueConstraint(fields=('docente', 'comision', 'fecha_inicio', 'fecha_fin'), name='uq_designacion_exact'),
        ),
    ]
