# Generated by Django 5.2.7 on 2025-10-05 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('anio', models.PositiveIntegerField(default=1)),
                ('cuatrimestre', models.PositiveIntegerField(default=1)),
                ('tipo_asignatura', models.CharField(choices=[('OBLIGATORIA', 'Obligatoria'), ('OPTATIVA', 'Optativa')], max_length=20)),
                ('tipo_duracion', models.CharField(choices=[('ANUAL', 'Anual'), ('CUATRIMESTRAL', 'Cuatrimestral')], max_length=20)),
                ('horas_teoria', models.PositiveIntegerField(default=0)),
                ('horas_practica', models.PositiveIntegerField(default=0)),
                ('horas_semanales', models.PositiveIntegerField(default=0)),
                ('horas_totales', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('TECNICATURA', 'Tecnicatura'), ('DIPLOMATURA', 'Diplomatura'), ('PREGRADO', 'Pregrado'), ('GRADO', 'Grado'), ('POSGRADO', 'Posgrado'), ('MAESTRIA', 'Maestria')], max_length=20)),
                ('esta_vigente', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dedicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('turno', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], max_length=20)),
                ('promocionable', models.BooleanField(default=False)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='gestion_academica.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carreras', models.ManyToManyField(blank=True, related_name='coordinadores', to='gestion_academica.carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_academica.cargo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to=settings.AUTH_USER_MODEL)),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_academica.modalidad')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='instituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.instituto'),
        ),
        migrations.CreateModel(
            name='ParametrosRegimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_min_semanal', models.PositiveIntegerField()),
                ('horas_max_semanal', models.PositiveIntegerField()),
                ('horas_min_anual', models.PositiveIntegerField()),
                ('horas_max_anual', models.PositiveIntegerField()),
                ('max_asignaturas', models.PositiveIntegerField()),
                ('dedicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.dedicacion')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Designacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo_designacion', models.CharField(choices=[('TITULAR', 'Titular'), ('INTERINO', 'Interino'), ('SUPLENTE', 'Suplente')], max_length=20)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.comision')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.docente')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.parametrosregimen')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDeEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('esta_vigente', models.BooleanField(default=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='planes/')),
                ('asignaturas', models.ManyToManyField(through='gestion_academica.PlanAsignatura', to='gestion_academica.asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.carrera')),
            ],
        ),
        migrations.AddField(
            model_name='planasignatura',
            name='plan_de_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.plandeestudio'),
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('emisor', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('anio', models.IntegerField()),
            ],
            options={
                'unique_together': {('tipo', 'emisor', 'numero', 'anio')},
            },
        ),
        migrations.AddField(
            model_name='plandeestudio',
            name='resolucion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestion_academica.resolucion'),
        ),
        migrations.CreateModel(
            name='Correlativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativa_requerida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_requisito_para', to='gestion_academica.planasignatura')),
                ('plan_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlativas_requeridas', to='gestion_academica.planasignatura')),
            ],
            options={
                'unique_together': {('plan_asignatura', 'correlativa_requerida')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='planasignatura',
            unique_together={('plan_de_estudio', 'asignatura')},
        ),
    ]
