# Generated by Django 5.2.7 on 2025-11-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
