# Generated by Django 5.2.7 on 2025-10-05 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designacion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designaciones', to='gestion_academica.docente'),
        ),
    ]
