# Generated by Django 5.2.7 on 2025-11-03 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designacion',
            name='dedicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designaciones', to='gestion_academica.dedicacion'),
        ),
        migrations.AddField(
            model_name='designacion',
            name='modalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designaciones', to='gestion_academica.modalidad'),
        ),
        migrations.AlterField(
            model_name='designacion',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designaciones', to='gestion_academica.parametrosregimen'),
        ),
    ]
