# Generated by Django 5.2.7 on 2025-10-20 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='anio',
        ),
        migrations.AddField(
            model_name='planasignatura',
            name='anio',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('emisor', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-anio', 'emisor', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'emisor', 'numero', 'anio'), name='uq_documento_identificador')],
            },
        ),
        migrations.AlterField(
            model_name='designacion',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designaciones', to='gestion_academica.documento'),
        ),
        migrations.AlterField(
            model_name='plandeestudio',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes', to='gestion_academica.documento'),
        ),
    ]
