# Generated by Django 5.2.7 on 2025-11-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreracoordinacion',
            name='creado_por',
        ),
        migrations.AlterField(
            model_name='carreracoordinacion',
            name='coordinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinaciones_creadas', to='gestion_academica.coordinador'),
        ),
    ]
