# Generated by Django 5.2.7 on 2025-11-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0002_carreracoordinacion_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designacion',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
