# Generated by Django 5.2.7 on 2025-11-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0002_remove_carreracoordinacion_creado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandeestudio',
            name='resolucion',
        ),
        migrations.DeleteModel(
            name='Resolucion',
        ),
    ]
