# Generated by Django 5.2.7 on 2025-11-13 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0002_carreracoordinacion_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreracoordinacion',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carreracoordinacion',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
