# Generated by Django 5.2.7 on 2025-11-14 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0002_carreracoordinacion_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designacion',
            name='horas_frente_alumnos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('DOCENTES_POR_DEDICACION', 'Docentes por dedicación'), ('DOCENTES_POR_MODALIDAD', 'Docentes por modalidad'), ('HORAS_POR_DOCENTE', 'Horas frente a alumnos por docente'), ('DESIGNACIONES_CARRERA', 'Designaciones por asignatura/carrera'), ('HISTORIAL_DOCENTE', 'Evolución histórica de designaciones de un docente')], help_text='Tipo de reporte exportado (ej: docentes por dedicación).', max_length=50)),
                ('formato', models.CharField(choices=[('CSV', 'Archivo CSV'), ('XLSX', 'Archivo Excel'), ('PDF', 'Archivo PDF')], help_text='Formato de exportación (CSV, XLSX, PDF).', max_length=10)),
                ('filtros', models.JSONField(blank=True, help_text='Filtros aplicados (carrera, periodo, rango fechas, dedicación, modalidad, etc.).', null=True)),
                ('generado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en la que se generó el archivo.')),
                ('exito', models.BooleanField(default=True, help_text='Indica si la exportación fue exitosa.')),
                ('mensaje_error', models.TextField(blank=True, help_text='Detalle del error en caso de fallar la generación del archivo.', null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario (coordinador) que realizó la exportación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exportaciones_estadisticas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Exportación de Estadísticas',
                'verbose_name_plural': 'Registros de Exportación de Estadísticas',
                'ordering': ['-generado_en'],
            },
        ),
    ]
