# Generated by Django 5.2.7 on 2025-11-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0003_alter_carreracoordinacion_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarionotificacion',
            name='fecha_recordatorio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
