# Generated by Django 5.2.7 on 2025-11-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0003_designacion_horas_frente_alumnos_exportlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designacion',
            name='horas_frente_alumnos',
        ),
    ]
