# Generated by Django 5.2.7 on 2025-11-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0003_designacion_activo'),
        ('gestion_academica', '0004_usuarionotificacion_fecha_recordatorio'),
    ]

    operations = [
    ]
