# Generated by Django 5.2.7 on 2025-11-15 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0005_merge_20251113_1915'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comision',
            name='uq_comision_asignatura_nombre',
        ),
        migrations.RenameField(
            model_name='parametrosregimen',
            old_name='horas_max_actual',
            new_name='horas_max_anual',
        ),
        migrations.RenameField(
            model_name='parametrosregimen',
            old_name='horas_min_actual',
            new_name='horas_min_anual',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='horas_practica',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='horas_semanales',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='horas_teoria',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='horas_totales',
        ),
        migrations.RemoveField(
            model_name='comision',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='designacion',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='designacion',
            name='regimen',
        ),
        migrations.AddField(
            model_name='comision',
            name='plan_asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='gestion_academica.planasignatura'),
        ),
        migrations.AddField(
            model_name='planasignatura',
            name='horas_practica',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planasignatura',
            name='horas_semanales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planasignatura',
            name='horas_teoria',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planasignatura',
            name='horas_totales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caracter',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dedicacion',
            name='nombre',
            field=models.CharField(choices=[('SIMPLE', 'simple'), ('SEMIEXCLUSIVA', 'semiexclusiva'), ('EXCLUSIVA', 'exclusiva')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('RESOLUCION', 'resolucion'), ('ORDENANZA', 'ordenanza')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='comision',
            constraint=models.UniqueConstraint(fields=('plan_asignatura', 'nombre'), name='uq_comision_asignatura_nombre'),
        ),
    ]
