# Generated by Django 5.2.7 on 2025-11-15 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0006_remove_comision_uq_comision_asignatura_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='plan_asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='gestion_academica.planasignatura'),
        ),
    ]
