# Generated by Django 5.2.7 on 2025-11-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0004_remove_designacion_horas_frente_alumnos'),
        ('gestion_academica', '0007_alter_comision_plan_asignatura'),
    ]

    operations = [
    ]
