# Generated by Django 5.2.7 on 2025-11-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0008_merge_20251118_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidad',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
