# Generated by Django 5.2.7 on 2025-11-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0009_alter_modalidad_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='cantidad_materias',
        ),
    ]
