from .admin_permissions import EsAdministrador
from .coordinador_permissions import EsCoordinadorDeCarrera
from .docente_permissions import EsDocente
from .editar_usuario_permissions import UsuarioViewSetPermission
