from .admin_permissions import EsAdministrador
from .coordinador_permissions import EsCoordinadorDeCarrera
from .docente_permissions import EsDocente
from .coordinador_o_docente import IsCoordinadorOrDocente
